// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CityUIClient is the client API for CityUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CityUIClient interface {
	// ListPlaceSpecs returns a list of Place that can be started through the UI.
	ListPlaceSpecs(ctx context.Context, in *ListPlaceSpecsRequest, opts ...grpc.CallOption) (CityUI_ListPlaceSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type cityUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCityUIClient(cc grpc.ClientConnInterface) CityUIClient {
	return &cityUIClient{cc}
}

func (c *cityUIClient) ListPlaceSpecs(ctx context.Context, in *ListPlaceSpecsRequest, opts ...grpc.CallOption) (CityUI_ListPlaceSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CityUI_ServiceDesc.Streams[0], "/v1.CityUI/ListPlaceSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cityUIListPlaceSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CityUI_ListPlaceSpecsClient interface {
	Recv() (*ListPlaceSpecsResponse, error)
	grpc.ClientStream
}

type cityUIListPlaceSpecsClient struct {
	grpc.ClientStream
}

func (x *cityUIListPlaceSpecsClient) Recv() (*ListPlaceSpecsResponse, error) {
	m := new(ListPlaceSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cityUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CityUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityUIServer is the server API for CityUI service.
// All implementations must embed UnimplementedCityUIServer
// for forward compatibility
type CityUIServer interface {
	// ListPlaceSpecs returns a list of Place that can be started through the UI.
	ListPlaceSpecs(*ListPlaceSpecsRequest, CityUI_ListPlaceSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCityUIServer()
}

// UnimplementedCityUIServer must be embedded to have forward compatible implementations.
type UnimplementedCityUIServer struct {
}

func (UnimplementedCityUIServer) ListPlaceSpecs(*ListPlaceSpecsRequest, CityUI_ListPlaceSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListPlaceSpecs not implemented")
}
func (UnimplementedCityUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCityUIServer) mustEmbedUnimplementedCityUIServer() {}

// UnsafeCityUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CityUIServer will
// result in compilation errors.
type UnsafeCityUIServer interface {
	mustEmbedUnimplementedCityUIServer()
}

func RegisterCityUIServer(s grpc.ServiceRegistrar, srv CityUIServer) {
	s.RegisterService(&CityUI_ServiceDesc, srv)
}

func _CityUI_ListPlaceSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPlaceSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CityUIServer).ListPlaceSpecs(m, &cityUIListPlaceSpecsServer{stream})
}

type CityUI_ListPlaceSpecsServer interface {
	Send(*ListPlaceSpecsResponse) error
	grpc.ServerStream
}

type cityUIListPlaceSpecsServer struct {
	grpc.ServerStream
}

func (x *cityUIListPlaceSpecsServer) Send(m *ListPlaceSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CityUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CityUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CityUI_ServiceDesc is the grpc.ServiceDesc for CityUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CityUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CityUI",
	HandlerType: (*CityUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CityUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPlaceSpecs",
			Handler:       _CityUI_ListPlaceSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "city-ui.proto",
}
